# Generated by Django 4.2.3 on 2023-07-15 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='camera',
            options={'ordering': ['club', 'ip'], 'verbose_name': 'камера видеонаблюдения', 'verbose_name_plural': 'камеры видеонаблюдения'},
        ),
        migrations.AlterModelOptions(
            name='club',
            options={'ordering': ['address'], 'verbose_name': 'компьютерные клубы', 'verbose_name_plural': 'компьютерные клубы'},
        ),
    ]
